import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'core/api_client.dart';
import 'firebase_options.dart';
import 'providers/auth_provider.dart';
import 'providers/customer_provider.dart';
import 'screens/auth/login_screen.dart';
import 'screens/splash_screen.dart';
import 'theme/app_colors.dart';
import 'theme/app_text.dart';
import 'theme/app_theme.dart';

/// The navigator, reachable from outside the widget tree.
///
/// Only one thing needs it: the 401 handler in [ApiClient], which fires from a
/// Dio interceptor where there is no `BuildContext` to be had.
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Options come from firebase_options.dart, generated by `flutterfire
  // configure` — never hand-edited. The Google Services Gradle plugin still
  // needs android/app/google-services.json at build time; passing the options
  // explicitly is what makes startup independent of it.
  Object? firebaseError;
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // A missing or malformed config must not become a white screen. The app
    // still starts and says exactly what is wrong, which is the difference
    // between a five-minute fix and an afternoon.
    firebaseError = e;
    debugPrint('Firebase.initializeApp() failed: $e');
  }

  runApp(NakhatFinjanApp(firebaseError: firebaseError));
}

class NakhatFinjanApp extends StatelessWidget {
  const NakhatFinjanApp({super.key, this.firebaseError});

  /// Non-null when Firebase could not start. Sign-in cannot work in that state,
  /// so the app shows [_FirebaseSetupScreen] instead of the splash.
  final Object? firebaseError;

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // Both are cheap to build: they construct a Dio and a secure-storage
        // handle and make no call until something asks them to.
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => CustomerProvider()),
      ],
      child: Builder(
        builder: (context) {
          // Wired here rather than in main() because it needs the providers
          // above it in the tree. Clearing the session and returning to login
          // is idempotent, so the several calls a burst of 401s produces
          // collapse into one visible outcome.
          ApiClient.onUnauthorized = () {
            final navigator = navigatorKey.currentState;
            if (navigator == null) return;

            context.read<AuthProvider>().signOut();
            context.read<CustomerProvider>().clear();
            navigator.pushAndRemoveUntil(
              MaterialPageRoute<void>(builder: (_) => const LoginScreen()),
              (route) => false,
            );
          };

          return MaterialApp(
            title: 'نكهة فنجان',
            navigatorKey: navigatorKey,
            debugShowCheckedModeBanner: false,
            theme: buildAppTheme(),
            // The whole app is Arabic, so direction is a constant rather than
            // something derived per-locale. This wraps the navigator itself,
            // which is what gets dialogs, bottom sheets and route transitions
            // to lay out and slide the right way too.
            //
            // `locale: Locale('ar')` is deliberately NOT set alongside it.
            // Declaring the locale without a MaterialLocalizations delegate
            // that supports it throws at build time, and the delegate needs
            // flutter_localizations — an SDK package, but still a pubspec
            // entry, so it is left for you to approve. Every string the app
            // renders is its own and already Arabic; what is missing is the
            // framework's share: the text-selection menu, date pickers,
            // semantics labels.
            //
            // TODO(i18n): add to pubspec.yaml —
            //   flutter_localizations:
            //     sdk: flutter
            // then set localizationsDelegates to the three Global*Localizations
            // delegates, and restore locale / supportedLocales here.
            builder: (context, child) => Directionality(
              textDirection: TextDirection.rtl,
              child: child ?? const SizedBox.shrink(),
            ),
            home: firebaseError == null
                ? const SplashScreen()
                : _FirebaseSetupScreen(error: firebaseError!),
          );
        },
      ),
    );
  }
}

/// Shown when `Firebase.initializeApp()` failed.
///
/// Deliberately in English and deliberately blunt: the only person who can ever
/// see this is a developer running a build whose Firebase config is missing, and
/// an Arabic apology would tell them nothing about how to fix it. It cannot
/// reach a customer — a release build without the config would fail long before
/// the store.
class _FirebaseSetupScreen extends StatelessWidget {
  const _FirebaseSetupScreen({required this.error});

  final Object error;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(AppMetrics.screenPadding),
          child: Directionality(
            textDirection: TextDirection.ltr,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(
                  Icons.warning_amber_rounded,
                  size: 42,
                  color: AppColors.deduct,
                ),
                const SizedBox(height: 18),
                Text(
                  'Firebase is not configured',
                  style: AppText.authTitle.copyWith(fontSize: 22),
                ),
                const SizedBox(height: 12),
                Text(
                  'Phone sign-in cannot run without it. Drop the project\'s '
                  'google-services.json into android/app/ and rebuild — a hot '
                  'restart is not enough, the Gradle plugin reads it at build '
                  'time.',
                  style: AppText.subtitle.copyWith(height: 1.6),
                ),
                const SizedBox(height: 20),
                Text('$error', style: AppText.rowMeta),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
